-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 00:39:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `POSLOVNICA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `POSLOVNICA` ;

CREATE TABLE IF NOT EXISTS `POSLOVNICA` (
  `idPoslovnice` INT NOT NULL,
  `brojTelefona` VARCHAR(20) NOT NULL,
  `adresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPoslovnice`),
  UNIQUE INDEX `idPoslovnice_UNIQUE` (`idPoslovnice` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZAPOSLENI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ZAPOSLENI` ;

CREATE TABLE IF NOT EXISTS `ZAPOSLENI` (
  `idZaposlenog` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `plata` DECIMAL(10,2) NOT NULL,
  `pozicija` VARCHAR(45) NOT NULL,
  `idPoslovnice` INT NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `lozinka` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZaposlenog`),
  INDEX `idPoslovnice_idx` (`idPoslovnice` ASC) VISIBLE,
  CONSTRAINT `zaposleni_idPoslovnice`
    FOREIGN KEY (`idPoslovnice`)
    REFERENCES `POSLOVNICA` (`idPoslovnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PREVOZ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PREVOZ` ;

CREATE TABLE IF NOT EXISTS `PREVOZ` (
  `idPrevoza` INT NOT NULL AUTO_INCREMENT,
  `tipPrevoza` VARCHAR(45) NOT NULL,
  `nazivKompanije` VARCHAR(45) NOT NULL,
  `cijena` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idPrevoza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SMJESTAJ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SMJESTAJ` ;

CREATE TABLE IF NOT EXISTS `SMJESTAJ` (
  `idSmjestaja` INT NOT NULL AUTO_INCREMENT,
  `nazivSmjestaja` VARCHAR(45) NOT NULL,
  `vrstaSmjestaja` VARCHAR(45) NOT NULL,
  `lokacija` VARCHAR(45) NOT NULL,
  `brojZvjezdica` VARCHAR(45) NOT NULL,
  `pogodnosti` VARCHAR(45) NOT NULL,
  `cijena` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idSmjestaja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ARANZMAN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ARANZMAN` ;

CREATE TABLE IF NOT EXISTS `ARANZMAN` (
  `idAranzmana` INT NOT NULL AUTO_INCREMENT,
  `nazivDestinacije` VARCHAR(45) NOT NULL,
  `cijena` DECIMAL(10,2) NOT NULL,
  `termin` DATE NOT NULL,
  `trajanje` VARCHAR(45) NOT NULL,
  `VODIC_idVodica` INT NOT NULL,
  `OSIGURANJE_idOsiguranja` INT NOT NULL,
  `PREVOZ_idPrevoza` INT NOT NULL,
  `SMJESTAJ_idSmjestaja` INT NOT NULL,
  PRIMARY KEY (`idAranzmana`),
  INDEX `fk_ARANZMAN_PREVOZ1_idx` (`PREVOZ_idPrevoza` ASC) VISIBLE,
  INDEX `fk_ARANZMAN_SMJESTAJ1_idx` (`SMJESTAJ_idSmjestaja` ASC) VISIBLE,
  CONSTRAINT `fk_ARANZMAN_PREVOZ1`
    FOREIGN KEY (`PREVOZ_idPrevoza`)
    REFERENCES `PREVOZ` (`idPrevoza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARANZMAN_SMJESTAJ1`
    FOREIGN KEY (`SMJESTAJ_idSmjestaja`)
    REFERENCES `SMJESTAJ` (`idSmjestaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USLUGA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USLUGA` ;

CREATE TABLE IF NOT EXISTS `USLUGA` (
  `idUsluge` INT NOT NULL AUTO_INCREMENT,
  `tipUsluge` VARCHAR(45) NOT NULL,
  `cijena` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idUsluge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KLIJENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KLIJENT` ;

CREATE TABLE IF NOT EXISTS `KLIJENT` (
  `idKlijenta` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `brojTelefona` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `datumRodjenja` DATE NOT NULL,
  PRIMARY KEY (`idKlijenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NACIN_PLACANJA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NACIN_PLACANJA` ;

CREATE TABLE IF NOT EXISTS `NACIN_PLACANJA` (
  `idNacinaPlacanja` INT NOT NULL,
  `nazivNacinaPlacanja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNacinaPlacanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REZERVACIJA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REZERVACIJA` ;

CREATE TABLE IF NOT EXISTS `REZERVACIJA` (
  `idRezervacije` INT NOT NULL AUTO_INCREMENT,
  `datumRezervacije` DATE NOT NULL,
  `ukupnaCijena` DECIMAL(10,2) NOT NULL,
  `idKlijenta` INT NOT NULL,
  `idAranzmana` INT NOT NULL,
  `idZaposlenog` INT NOT NULL,
  `NACIN_PLACANJA_idNacinaPlacanja` INT NOT NULL,
  `POSLOVNICA_idPoslovnice` INT NOT NULL,
  PRIMARY KEY (`idRezervacije`),
  INDEX `idAranzmana_idx` (`idAranzmana` ASC) VISIBLE,
  INDEX `idKlijenta_idx` (`idKlijenta` ASC) VISIBLE,
  INDEX `idZaposlenog_idx` (`idZaposlenog` ASC) VISIBLE,
  INDEX `fk_REZERVACIJA_NACIN_PLACANJA1_idx` (`NACIN_PLACANJA_idNacinaPlacanja` ASC) VISIBLE,
  INDEX `fk_REZERVACIJA_POSLOVNICA1_idx` (`POSLOVNICA_idPoslovnice` ASC) VISIBLE,
  CONSTRAINT `rezervacija_idAranzmana`
    FOREIGN KEY (`idAranzmana`)
    REFERENCES `ARANZMAN` (`idAranzmana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rezervacija_iidKlijenta`
    FOREIGN KEY (`idKlijenta`)
    REFERENCES `KLIJENT` (`idKlijenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rezervacija_idZaposlenog`
    FOREIGN KEY (`idZaposlenog`)
    REFERENCES `ZAPOSLENI` (`idZaposlenog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REZERVACIJA_NACIN_PLACANJA1`
    FOREIGN KEY (`NACIN_PLACANJA_idNacinaPlacanja`)
    REFERENCES `NACIN_PLACANJA` (`idNacinaPlacanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REZERVACIJA_POSLOVNICA1`
    FOREIGN KEY (`POSLOVNICA_idPoslovnice`)
    REFERENCES `POSLOVNICA` (`idPoslovnice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TERMIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TERMIN` ;

CREATE TABLE IF NOT EXISTS `TERMIN` (
  `idTermina` INT NOT NULL,
  `datumPocetka` DATE NOT NULL,
  `datumKraja` DATE NOT NULL,
  `brojSlobodnihMjesta` INT NOT NULL,
  `idAranzmana` INT NOT NULL,
  PRIMARY KEY (`idTermina`),
  INDEX `idAranzmana_idx` (`idAranzmana` ASC) VISIBLE,
  CONSTRAINT `termin_idAranzmana`
    FOREIGN KEY (`idAranzmana`)
    REFERENCES `ARANZMAN` (`idAranzmana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `REZERVACIJA_has_USLUGA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `REZERVACIJA_has_USLUGA` ;

CREATE TABLE IF NOT EXISTS `REZERVACIJA_has_USLUGA` (
  `REZERVACIJA_idRezervacije` INT NOT NULL,
  `USLUGA_idUsluge` INT NOT NULL,
  PRIMARY KEY (`REZERVACIJA_idRezervacije`, `USLUGA_idUsluge`),
  INDEX `fk_REZERVACIJA_has_USLUGA_USLUGA1_idx` (`USLUGA_idUsluge` ASC) VISIBLE,
  INDEX `fk_REZERVACIJA_has_USLUGA_REZERVACIJA1_idx` (`REZERVACIJA_idRezervacije` ASC) VISIBLE,
  CONSTRAINT `fk_REZERVACIJA_has_USLUGA_REZERVACIJA1`
    FOREIGN KEY (`REZERVACIJA_idRezervacije`)
    REFERENCES `REZERVACIJA` (`idRezervacije`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REZERVACIJA_has_USLUGA_USLUGA1`
    FOREIGN KEY (`USLUGA_idUsluge`)
    REFERENCES `USLUGA` (`idUsluge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
